services:
  live-in-crawler:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    tty: true
    volumes:
      - .:/app
    networks:
      - live_in_network

networks:
  live_in_network:
    external: true
